### ISSUE TITLE
One base64 image from several AND download zip archive

### ISSUE THREAD

**Issue by kirikl7** [backgroundColor/docToHtml#1]
Hello, you are probably the only one who has implemented this project so well, because everything else is nonsense...
But there are a few questions about it.
Look, the images converted to base64 are in order one after another (![2022-04-06_10-58-45](https://user-images.githubusercontent.com/103101830/161925547-8dbf17ae-e379-4506-8690-7f5296ab2e8d.png)), I would like them to appear in the form in which they are in the Word, will it be possible to do this? (![2022-04-06_10-45-25](https://user-images.githubusercontent.com/103101830/161925016-4fbd2b2e-0182-4625-a367-80e586d31555.png))
And here's one more thing, is it possible to make it possible to upload several docx files at once and they would all be saved in a separate "html" folder or would they be downloaded in one zip archive?
Thanks!

**Comment by backgroundColor** [comment]
Sorry, I just saw this issue, the project belongs to a long time ago, multi-file upload and conversion is not supported, if necessary, you can modify it according to the project
